### ISSUE TITLE
CTRL+F search across multiple tabs

### ISSUE THREAD

**Issue by Bamajon1974** [igorlogius/find-in-tabs#1]
Good afternoon. How are you doing? 

Question...do you have a FireFox extension that performs a CTRL+F/find on keyword search across multiple tabs? 

Thanks!

**Comment by Bamajon1974** [comment]
Ok. Let me know where to download your xpi file and I will test it out and then go over features. 

Thank you!

**Comment by igorlogius** [comment]
https://addons.mozilla.org/en-US/firefox/addon/find-in-tabs/

Happy testing.

I'll close this issue.

You can open new ones for each improvment suggestions or feature request, you feel might be useful or necessary.

**Comment by Bamajon1974** [comment]
Awesome. Thank you. I will test it out tomorrow. Where should I make feature requests and/or bug fix requests?

**Comment by igorlogius** [comment]
> Where should I make feature requests and/or bug fix requests?

https://github.com/igorlogius/find-in-tabs/issues/new/choose
